##server port
#server:
#  port: 8889
##student
#student:
#  id: 2
#  name: wang
#  user-name: wjp
#  age: 22
#  hobby:
#    - A
#    - B
#    - C
#  lists:
#    - ${student.name}
#    - ${b}
#    - ${a}
#  maps:
#    k1: v1
#    k2: v2
#  sets:
#    - A
#    - B
#    - C
#    - C
#  birth: 2020/03/30 18:18
#a: aaaa
#b: ${random.int[1,100]}